import 'package:flutter/material.dart';

void main() {
  runApp(const BilibiliApp());
  }

  class BilibiliApp extends StatelessWidget {
    const BilibiliApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  debugShowCheckedModeBanner: false, // 去掉右上角的 "DEBUG" 标签
                        theme: ThemeData(
                                brightness: Brightness.light,
                                        primarySwatch: Colors.pink,
                                                fontFamily: 'sans-serif',
                                                      ),
                                                            home: const HomePage(),
                                                                );
                                                                  }
                                                                  }

                                                                  class HomePage extends StatelessWidget {
                                                                    const HomePage({super.key});

                                                                      @override
                                                                        Widget build(BuildContext context) {
                                                                            return Scaffold(
                                                                                  appBar: AppBar(
                                                                                          title: const Text(
                                                                                                    '哔哩哔哩',
                                                                                                              style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                                                                                                                      ),
                                                                                                                              backgroundColor: const Color(0xfffb7299), // B站粉色
                                                                                                                                    ),
                                                                                                                                          body: ListView(
                                                                                                                                                  padding: const EdgeInsets.all(8.0),
                                                                                                                                                          children: const [
                                                                                                                                                                    VideoCard(
                                                                                                                                                                                imageUrl: 'https://i0.hdslb.com/bfs/archive/c9335552d77360216b3e95717614299499314963.jpg',
                                                                                                                                                                                            title: '【Flutter】从零开始的开发环境搭建之旅',
                                                                                                                                                                                                        author: 'Gemini-AI',
                                                                                                                                                                                                                    views: '168.8万观看',
                                                                                                                                                                                                                                timestamp: '4小时前',
                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                    VideoCard(
                                                                                                                                                                                                                                                                imageUrl: 'https://i0.hdslb.com/bfs/archive/09fc1859183406548b80cf4b6385676e82a037b5.jpg',
                                                                                                                                                                                                                                                                            title: '如何在 Codespaces 中优雅地写代码',
                                                                                                                                                                                                                                                                                        author: 'GitHub',
                                                                                                                                                                                                                                                                                                    views: '233.3万观看',
                                                                                                                                                                                                                                                                                                                timestamp: '1天前',
                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                              class VideoCard extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                final String imageUrl;
                                                                                                                                                                                                                                                                                                                                                  final String title;
                                                                                                                                                                                                                                                                                                                                                    final String author;
                                                                                                                                                                                                                                                                                                                                                      final String views;
                                                                                                                                                                                                                                                                                                                                                        final String timestamp;

                                                                                                                                                                                                                                                                                                                                                          const VideoCard({
                                                                                                                                                                                                                                                                                                                                                              super.key,
                                                                                                                                                                                                                                                                                                                                                                  required this.imageUrl,
                                                                                                                                                                                                                                                                                                                                                                      required this.title,
                                                                                                                                                                                                                                                                                                                                                                          required this.author,
                                                                                                                                                                                                                                                                                                                                                                              required this.views,
                                                                                                                                                                                                                                                                                                                                                                                  required this.timestamp,
                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                      @override
                                                                                                                                                                                                                                                                                                                                                                                        Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                            return Card(
                                                                                                                                                                                                                                                                                                                                                                                                  margin: const EdgeInsets.only(bottom: 16.0),
                                                                                                                                                                                                                                                                                                                                                                                                        elevation: 4.0,
                                                                                                                                                                                                                                                                                                                                                                                                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                                                                                                                                                                                                                                                                                                                                                                                                    child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                            crossAxisAlignment: CrossAxisAlignment.stretch,
                                                                                                                                                                                                                                                                                                                                                                                                                                    children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                              Image.network(
                                                                                                                                                                                                                                                                                                                                                                                                                                                          imageUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fit: BoxFit.cover,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  height: 200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(12.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            crossAxisAlignment: CrossAxisAlignment.start,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style: const TextStyle(fontSize: 18.0, fontWeight: FontWeight.bold),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                maxLines: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  overflow: TextOverflow.ellipsis,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 8.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '$author · $views · $timestamp',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(fontSize: 14.0, color: Colors.grey[600]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }